name: upgrade nodes on test env

on:
  push:
    branches:
      - wojciechos/deploy_workflow
  release:
    types: [created]

jobs:
  upgrade_nodes_on_test_env:
    runs-on: ubuntu-latest
    steps:
    - name: Define docker image tag
      run: echo "DOCKER_IMAGE_TAG=${{ github.actor }}-${{ github.sha }}" >> $GITHUB_ENV

    - name: Trigger build_and_push_docker_image
      id: trigger-build
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Build and publish Docker image
        token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
        ref: ${{ github.ref }}
        inputs: '{"tag": "${{ env.DOCKER_IMAGE_TAG }}"}'

    - name: Wait for build_and_push_docker_image workflow to complete
      uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: build_and_push_docker_image
        intervalSeconds: 60
        timeoutSeconds: 1500

    - name: Remove old Juno containers and start new ones
      if: steps.wait-for-build.outputs.conclusion == 'success'
      uses: appleboy/ssh-action@v0.1.8
      env:
        HOST: ${{ github.event_name == 'push' && secrets.STAGING_IP || github.event_name == 'release' && secrets.RELEASE_IP }}
      with:
        host: ${{ env.HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        envs: DOCKER_IMAGE
        script: |
            port=6060
            for network in mainnet goerli goerli2; do
                docker stop juno_$network
                docker rm juno_$network
                docker run -d \
                    --name juno_$network \
                    -p $port:$port \
                    -v /root/juno_$network:/var/lib/juno \
                    nethermindeth/juno:${{ env.DOCKER_IMAGE_TAG }} \
                    --db-path /var/lib/juno \
                    --rpc-port $port \
                    --network $network \
                    --colour=false \
                    $(if [ "$network" = "mainnet" ]; then echo "--pprof"; fi)
                port=$((port+1))
                nohup sh -c "docker logs -f juno_$network > /var/log/juno_logs_$network.log" &>/dev/null &
            done